### ISSUE TITLE
Adding model parameters - not a simple loop

### ISSUE THREAD

**Issue by JohnAbel** [JohnAbel/gillespy#8]
It would be useful if, having two arrays:
p_names = ['k1', 'k2']
p_values = [1, 2]
we could loop to add them.

I normally do that with:
for i in xrange(num_parameters):
    self.add_parameter(gillespy.Parameter(name = p_names[i], expression = p_values[i]))

But then when we make a reaction:
r1 = gillespy.Reaction(reactants = x1, rate = k1) the rate is not defined. Is there a better way to do this?

**Comment by ahellander** [comment]
Since you don’t have a variable k1 in scope, the below flow does not make sense. I understand what you are after though. What would make sense would be to allow the rate argument to Reaction to be a string, then you can resolve it in the namespace of Parameter names internally in the library, i.e. you would extend the constructor of Reaction to allow to give


We need to discuss all this, from a bigger perspective. Do we want to keep the “well mixed part” of the APIs in gillespy and pyurdme to be compatible?

r1 = gillespy.Reaction(reactants = x1, rate = “k1")

I also think the loop below is a bit clunky. I would rather assemble all my parameter_name:value pairs in a dict, then extend add_parameter to allow bulk add with the dict as argument

parameters = {“k1”:1, “k2”:2}
self.add_parameters(parameters)

/Andreas

-------------------------------------------

Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Apr 2, 2015, at 7:08 PM, J.H. Abel <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be useful if, having two arrays:
p_names = ['k1', 'k2']
p_values = [1, 2]
we could loop to add them.

I normally do that with:
for i in xrange(num_parameters):
self.add_parameter(gillespy.Parameter(name = p_names[i], expression = p_values[i]))

But then when we make a reaction:
r1 = gillespy.Reaction(reactants = x1, rate = k1) the rate is not defined. Is there a better way to do this?

**Comment by JohnAbel** [comment]
Andreas: I agree with the use of a dict. I will be picking back up on this (getting StochKitODE to work as well) so we can definitely discuss tweaks.

**Comment by ahellander** [comment]
I would like us to discuss the design and see if whatever changes we make here, we also make in pyurdme, and vice versa.

/Andreas
-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Apr 2, 2015, at 7:57 PM, J.H. Abel <notifications@github.com<mailto:notifications@github.com>> wrote:


Andreas: I agree with the use of a dict. I will be picking back up on this (getting StochKitODE to work as well) so we can definitely discuss tweaks.

**Comment by JohnAbel** [comment]
I won't be making changes unless we decide to implement it in both
packages. It would make no sense to make them diverge.

On Thu, Apr 2, 2015 at 11:04 AM, Andreas Hellander <notifications@github.com
> wrote:

> I would like us to discuss the design and see if whatever changes we make
> here, we also make in pyurdme, and vice versa.
>
> /Andreas
> -------------------------------------------
> Andreas Hellander
> Associate Professor, Scientific Computing
> Division of Scientific Computing
> Department of Information Technology
> Uppsala University
>
> On Apr 2, 2015, at 7:57 PM, J.H. Abel <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
>
> Andreas: I agree with the use of a dict. I will be picking back up on this
> (getting StochKitODE to work as well) so we can definitely discuss tweaks.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/JohnAbel/gillespy/issues/8#issuecomment-88991873>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnAbel/gillespy/issues/8#issuecomment-88994363>.
>



-- 

*John H. Abel*
PhD Student, Chemical Engineering
University of California, Santa Barbara
Email: jha@engr.ucsb.edu
Tel: (401)787-4253

**Comment by ahellander** [comment]
We could discuss having

pyurdme.URDMEModel(gillespy.Model)

or

gillspy.Model(pyurdme.Model) (Model = the well-mixed library “model.py” in pyurdme)

then they would be formally tied together. But there are risks with that too.

Brian, what do you think?

/Andreas

-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Apr 2, 2015, at 8:07 PM, J.H. Abel <notifications@github.com<mailto:notifications@github.com>> wrote:

I won't be making changes unless we decide to implement it in both
packages. It would make no sense to make them diverge.

On Thu, Apr 2, 2015 at 11:04 AM, Andreas Hellander <notifications@github.com<mailto:notifications@github.com>
> wrote:

> I would like us to discuss the design and see if whatever changes we make
> here, we also make in pyurdme, and vice versa.
>
> /Andreas
> -------------------------------------------
> Andreas Hellander
> Associate Professor, Scientific Computing
> Division of Scientific Computing
> Department of Information Technology
> Uppsala University
>
> On Apr 2, 2015, at 7:57 PM, J.H. Abel <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
>
>
> Andreas: I agree with the use of a dict. I will be picking back up on this
> (getting StochKitODE to work as well) so we can definitely discuss tweaks.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/JohnAbel/gillespy/issues/8#issuecomment-88991873>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnAbel/gillespy/issues/8#issuecomment-88994363>.
>



--

*John H. Abel*
PhD Student, Chemical Engineering
University of California, Santa Barbara
Email: jha@engr.ucsb.edu<mailto:jha@engr.ucsb.edu>
Tel: (401)787-4253

**Comment by briandrawert** [comment]
I think we can easily have a converter function in pyurdme that can get called if the first argument to the constructor is a gillespy model, and vice versa.  But I don't think we can just do it without some logic behind the scenes.

**Comment by JohnAbel** [comment]
We have implemented some form of this, so I am closing it.
